name: haskell-elm-mongo-broadcast
version: 0.1.0.0
github: "mudont/haskell-elm-mongo-broadcast"
license: BSD3
author: "Author name here"
maintainer: "Author email here"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Broadcast selected Mongo changes to websocket clients

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - TemplateHaskell
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - TypeOperators
  - TypeFamilies
  - ConstraintKinds

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bson
  - bytestring
  - case-insensitive
  - classy-prelude
  - containers
  - data-has
  - exceptions
  - ghc-prim
  - http-types
  - jose
  - mongoDB
  - mtl
  - network
  - random
  - servant
  - servant-auth
  - servant-auth-server
  - servant-server
  - servant-websockets
  - split
  - stm
  - text
  - time
  - threads
  - uuid
  - wai
  - wai-app-static
  - wai-cors
  - wai-logger
  - wai-websockets
  - warp
  - websockets

_exe-defs: &exe-defaults
  source-dirs:
    - app
    - src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
library:
  source-dirs: src

executables:
  # mongo-broadcast:
  #   main: Main.hs
  #   <<: *exe-defaults
  ws-client:
    main: wsClient.hs
    <<: *exe-defaults
  ws-server:
    main: wsServer.hs
    <<: *exe-defaults
  chat-client:
    main: chatClient.hs
    <<: *exe-defaults
  tail-oplog:
    main: tailOplog.hs
    <<: *exe-defaults
  update-quotes-mongo:
    main: updateQuotesMongo.hs
    <<: *exe-defaults

tests:
  oplog-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
